apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworldchart.fullname" . }}
  labels:
    {{- include "helloworldchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalport }}
      targetPort: {{ .Values.service.internalport }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "helloworldchart.selectorLabels" . | nindent 4 }}
